#
# TABLE STRUCTURE FOR: messages
#

DROP TABLE IF EXISTS `messages`;

CREATE TABLE `messages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Идентификатор строки',
  `from_user_id` int(10) unsigned NOT NULL COMMENT 'Ссылка на отправителя сообщения',
  `to_user_id` int(10) unsigned NOT NULL COMMENT 'Ссылка на получателя сообщения',
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Текст сообщения',
  `is_important` tinyint(1) DEFAULT NULL COMMENT 'Признак важности',
  `is_delivered` tinyint(1) DEFAULT NULL COMMENT 'Признак доставки',
  `created_at` datetime DEFAULT current_timestamp() COMMENT 'Время создания строки',
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'Время обновления строки',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Сообщения';

INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (1, 60, 41, 'Non repudiandae quia mollitia odit. Vero veniam dolore maxime dolorum sed temporibus et quod. Voluptatum similique quam quidem accusantium dolor necessitatibus accusantium quia. Quasi distinctio at minima ea ratione consequatur.', 1, 0, '2021-04-01 05:34:53', '1985-04-18 07:56:22');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (2, 96, 91, 'Tempora quisquam nisi accusamus totam molestiae reiciendis. Dolor aut ut nisi officia.', 1, 0, '2002-07-03 23:29:03', '1993-09-25 23:21:06');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (3, 91, 74, 'Et facilis dolor dolorum consequatur atque. Beatae repellendus illum totam voluptatem ea sed. Ipsa laborum consequatur provident laborum. Hic minus sunt deserunt ullam nesciunt possimus aut nisi.', 0, 0, '2007-12-28 02:00:33', '2006-01-12 04:13:43');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (4, 58, 30, 'At voluptas unde distinctio ut aliquid. Facere eligendi vitae quia consectetur qui ipsam. Unde minima possimus sunt assumenda.', 1, 1, '1995-01-24 12:53:15', '2010-09-04 01:03:30');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (5, 23, 52, 'Voluptate quia eligendi molestiae cupiditate. Fuga atque qui dolor aperiam vero praesentium ea incidunt. Qui culpa reprehenderit atque est voluptate pariatur quos perferendis.', 0, 0, '2016-05-03 12:22:59', '1997-03-05 17:49:49');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (6, 17, 21, 'Qui et id temporibus. Et minima sequi pariatur cum. Ab necessitatibus impedit assumenda quis quia. Commodi qui nemo dolores neque perferendis.', 0, 1, '2020-02-11 22:07:07', '1999-03-18 12:04:41');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (7, 73, 0, 'Nulla quos ipsa assumenda occaecati. Rerum ea totam ullam saepe libero. Dolores modi dolor voluptate sed minus repellendus quia.', 0, 1, '1972-09-19 06:40:56', '2017-06-16 03:37:45');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (8, 50, 30, 'Eum praesentium et est dolor quas. Consequatur laborum nihil repudiandae nisi quia voluptatem occaecati ut. Numquam ea sed qui dicta aliquid eos qui sint. Voluptas vel exercitationem doloremque pariatur.', 1, 1, '2004-12-23 15:22:13', '1988-12-29 08:24:29');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (9, 28, 80, 'Rerum quia minima saepe. Assumenda cumque error dolores nemo veniam voluptas consequuntur aut. Similique quia aperiam et voluptatum est debitis ut.', 1, 0, '1998-08-12 05:12:23', '2003-12-23 01:43:51');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (10, 47, 22, 'Odio omnis ipsum vel magni aut earum laudantium. Fugit dolorem et eos quas. Quasi voluptatem voluptas voluptatum adipisci ut veniam iure facilis.', 1, 0, '2004-09-27 06:39:01', '1984-04-23 16:59:29');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (11, 59, 28, 'Officia id quam iste quod numquam iusto similique. Eum repellat mollitia libero dolorem facilis maxime harum. Veniam omnis tenetur repudiandae maxime occaecati enim sequi. Autem quia id quisquam dolore qui magnam esse eaque.', 1, 1, '2019-04-04 03:57:50', '2022-01-06 15:14:30');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (12, 28, 43, 'Quibusdam velit et commodi et quia dolores et repudiandae. Odit dicta et est. Quis ullam sapiente et voluptas suscipit odio aut et.', 1, 1, '1989-10-17 21:01:43', '1980-11-13 04:05:45');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (13, 39, 49, 'Maiores vel iste aliquid sed. Officia qui iste est ut iste quidem. Sit ut quos autem.', 1, 0, '1991-05-30 08:33:15', '1979-01-04 03:16:00');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (14, 54, 30, 'Qui maiores quae est ab adipisci perspiciatis numquam. Sapiente ducimus molestias delectus et modi sed possimus. Qui est omnis delectus possimus aspernatur est.', 1, 1, '1989-11-02 10:09:28', '1983-05-20 20:06:43');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (15, 26, 90, 'Quaerat quia voluptatem dolorem delectus vitae commodi qui. Sit sit iure non ut doloremque ut. Asperiores fugiat optio quis accusamus harum. Qui consequuntur molestiae quasi suscipit totam voluptatem et. Aliquid perspiciatis et ex soluta enim veritatis cumque.', 1, 0, '1972-07-31 06:43:06', '1979-10-12 02:02:16');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (16, 1, 61, 'Omnis perspiciatis voluptatem eos qui ut aut. Id hic ad culpa est temporibus recusandae. Harum dolor natus incidunt voluptatem necessitatibus. Dolores fugiat dolore illo molestiae.', 0, 0, '2000-05-16 12:06:11', '1972-01-09 09:22:23');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (17, 55, 30, 'Esse ipsa neque asperiores temporibus ea aut excepturi et. Dolore et exercitationem illum ipsa tempore consequatur. Aperiam porro voluptas non velit nobis ipsum excepturi. Tempora illo eaque saepe est et.', 1, 0, '1991-07-19 04:19:04', '1991-10-28 22:36:44');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (18, 38, 75, 'Consequatur quod dolor illum eius molestiae. Autem sit qui adipisci voluptatum. Animi eligendi quia rerum dolore. Aut labore voluptates sunt repellat dicta rerum. Qui unde vitae animi quaerat.', 0, 1, '2006-12-05 17:46:57', '1994-03-21 23:58:01');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (19, 81, 7, 'Molestias corrupti pariatur rerum id vel omnis in. Aliquid perspiciatis aliquid est rem architecto illum provident. A vero necessitatibus earum qui. Cupiditate quidem fugiat quidem adipisci nemo.', 1, 1, '1992-08-18 05:20:01', '1987-06-15 00:14:55');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (20, 99, 81, 'Quaerat dolor vitae consequuntur a. Est ea nostrum placeat vel voluptas omnis aspernatur. Asperiores ut id dignissimos placeat perferendis. Aperiam doloremque neque ad esse vero provident.', 0, 1, '1987-03-17 23:20:27', '1996-10-16 21:56:46');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (21, 43, 17, 'Vel qui omnis soluta hic dolor iste modi in. Quo et quo modi consequuntur animi nihil labore aperiam. Sit blanditiis sapiente aut eligendi. Sit tempora sed libero.', 0, 1, '2019-11-07 12:02:30', '1992-07-11 06:48:05');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (22, 21, 67, 'Nam et sint consequuntur optio exercitationem. Incidunt accusantium facere expedita magni voluptatum. Aliquid et dolorem voluptates quaerat rem pariatur. Facilis iure aliquid placeat quia.', 1, 1, '1975-01-03 04:15:31', '1999-10-04 22:23:15');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (23, 45, 60, 'Nihil dolore ut delectus ea. Nemo ipsam numquam ea. Velit et velit dolores et laudantium. Dolorum eligendi rerum fugiat corporis fuga.', 0, 1, '2019-06-19 09:07:56', '1975-09-18 20:35:14');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (24, 89, 68, 'Rerum soluta nobis nesciunt neque illum blanditiis consequatur. Animi qui qui odio illo maxime perspiciatis. Voluptas id eum aut perspiciatis eaque asperiores.', 0, 1, '1991-06-13 12:51:28', '1975-01-14 20:00:48');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (25, 63, 54, 'Delectus dolorem earum provident iure cupiditate. Illum quam quisquam consequatur. Voluptatem non aut et dolores. Aut tempore rerum ut reprehenderit.', 0, 0, '2005-06-26 03:45:19', '1997-07-29 02:52:53');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (26, 77, 27, 'Voluptatem praesentium temporibus facilis consequatur occaecati dicta. Quod numquam ea maiores nostrum sequi dolores ut. Labore aut consequatur quia perferendis possimus autem. Quisquam eum nulla voluptas omnis at et et ex.', 1, 1, '2021-05-30 01:21:58', '1990-08-12 19:15:04');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (27, 36, 67, 'Itaque omnis quo rerum suscipit assumenda quisquam ab. Sint cupiditate perferendis fugit minima. Nobis at non labore ab.', 0, 0, '1980-06-23 17:04:58', '1986-01-24 13:17:04');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (28, 39, 45, 'Dolores autem excepturi minima. Beatae quia assumenda quae qui cumque ut est. Reiciendis ut dignissimos ex et veniam vitae occaecati cupiditate. Qui ad qui consequuntur error quam nobis omnis vel.', 0, 1, '2009-10-02 11:56:34', '2005-02-22 09:30:49');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (29, 54, 58, 'Debitis distinctio rem rem dolores itaque quibusdam. Modi et magnam laborum placeat nemo eum ipsum. Sint hic neque nihil ut consequatur optio itaque.', 0, 1, '2020-10-12 14:29:16', '1999-02-12 10:51:54');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (30, 87, 51, 'Fuga a eos autem quis officia quia neque quia. Non dolor eos ut rerum. Necessitatibus veritatis explicabo et sunt. Et officiis est et ut nesciunt ut laboriosam sit.', 0, 0, '1986-11-05 12:00:51', '2013-06-26 02:22:34');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (31, 25, 18, 'Autem provident perferendis officia voluptatem adipisci. Assumenda ut aliquid omnis iste suscipit quia. Minus occaecati autem sed omnis. Aut officia sed omnis illo fuga.', 1, 0, '1976-09-20 21:37:51', '1997-10-05 16:36:05');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (32, 15, 10, 'Voluptas eius ipsum omnis enim qui. Est quia ipsa excepturi deleniti atque sed. Harum aspernatur non aut et et nisi. Eos enim nostrum voluptas aut est quam ex est.', 0, 1, '1980-04-20 16:44:10', '2007-05-28 21:54:28');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (33, 20, 76, 'Aperiam commodi perspiciatis vero excepturi aspernatur unde. Numquam culpa magni sit consequatur quasi. Praesentium incidunt ex aut et tenetur.', 1, 0, '2012-10-05 00:51:22', '2015-02-02 22:21:04');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (34, 78, 38, 'Error veritatis fugiat voluptas ratione quas rerum. Nostrum sapiente ut culpa et non tempora. Et laudantium debitis consequuntur maxime voluptatem voluptas at.', 0, 0, '1973-08-28 20:18:46', '2020-11-11 04:46:03');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (35, 11, 0, 'Suscipit doloremque magni dolorem nihil non quibusdam. Et voluptas magni doloribus at ut. Quaerat commodi quod et ut molestias.', 1, 0, '2016-02-27 18:22:13', '2003-05-03 23:50:37');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (36, 33, 83, 'Veritatis in quis sed quam tempora. Neque quaerat hic occaecati dolorem. Qui quia sit laudantium deleniti et voluptas.', 1, 0, '1982-12-29 01:43:32', '1979-10-30 14:55:19');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (37, 99, 36, 'Numquam tenetur odio rerum tempore quas. Sint et quidem nobis. Voluptatem dolor perferendis maxime. Enim dignissimos non itaque dolorum omnis laboriosam qui. Quia recusandae ut quia necessitatibus fuga voluptatem.', 1, 0, '1987-12-12 00:34:54', '1979-07-15 15:53:29');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (38, 22, 46, 'Quia dolore dolores repellat velit. Veniam ratione molestiae odio in laudantium. Ratione est minus dolorem optio. Ut est amet voluptas.', 1, 0, '2020-08-27 15:15:28', '2002-10-11 08:41:56');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (39, 93, 38, 'Debitis alias vitae ut consectetur neque. Quaerat sunt maiores magnam labore et quibusdam aut assumenda. Consequatur sequi quos vel ut.', 0, 0, '1994-05-22 00:56:04', '1983-02-25 10:32:20');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (40, 97, 28, 'Voluptatem iure numquam aut ex in. Enim distinctio laboriosam tempora deserunt est. Porro voluptates consequatur qui dolorem est.', 0, 1, '1982-11-18 22:49:31', '1982-02-01 13:10:39');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (41, 22, 85, 'Tenetur eum animi consequatur aperiam perspiciatis. Non nostrum quod sed voluptatibus nobis dolores et. Et error eaque eos quas maiores quis explicabo. Doloribus aut voluptatem aut sed odio nobis neque.', 1, 1, '1991-10-18 14:00:06', '2017-08-31 15:38:46');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (42, 73, 32, 'Odio sed aliquam qui voluptates officia accusantium at officia. Ducimus dolores voluptatem et non architecto aliquam similique. Quidem officia fuga beatae enim atque hic et. A at quae ut hic dolore.', 0, 0, '2017-04-29 22:28:27', '2000-10-12 04:10:37');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (43, 15, 39, 'Ea rerum necessitatibus et et corporis deleniti impedit. Possimus recusandae deleniti consectetur praesentium eius tenetur. Ut delectus itaque qui.', 0, 0, '1982-06-28 21:19:11', '1995-03-15 04:00:31');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (44, 85, 11, 'Fugiat quam delectus aut laudantium inventore explicabo molestiae. Voluptatum quaerat aperiam neque quibusdam ut. Aut sunt accusantium quia maxime fugit fugit.', 1, 0, '1981-06-04 19:11:31', '1997-10-05 13:38:59');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (45, 14, 47, 'Rem quae perspiciatis harum et sit quibusdam repellat. Cum quam facilis magni.', 0, 0, '2012-12-24 08:03:45', '2015-07-16 02:37:44');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (46, 90, 95, 'Ut ullam sunt qui iste tempore. Voluptates dolores qui et qui. Quaerat amet nihil laborum fugit iure in natus reiciendis.', 1, 1, '2007-12-29 15:33:54', '2014-05-15 15:49:06');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (47, 58, 52, 'Impedit hic recusandae qui voluptas in. Ut culpa dicta quod ut. Eum ex recusandae unde et dignissimos quibusdam.', 0, 1, '2018-06-18 19:41:42', '2003-09-27 10:13:57');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (48, 100, 92, 'Illo et sequi molestiae recusandae sed perferendis earum eos. Est quasi consectetur aliquam sit ratione provident modi nesciunt. Consequatur dolor asperiores delectus autem.', 1, 0, '2016-09-27 00:09:16', '2015-08-20 20:00:40');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (49, 47, 73, 'Repellat id officiis ducimus quas aut illum quia. Aut delectus ut doloremque veritatis ut et eius suscipit.', 0, 0, '1994-11-22 19:24:59', '2018-03-24 00:26:25');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (50, 7, 26, 'Et exercitationem ea et quis et. In consequatur est et aut totam repudiandae. Est voluptatem iure blanditiis harum. Esse sit eos maiores quis et voluptatem nemo.', 1, 0, '2020-09-21 08:14:05', '2006-12-27 16:40:36');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (51, 88, 24, 'Et sed vel perferendis sequi. Quam aut consequatur ullam autem soluta ut. In nihil voluptates deleniti in numquam.', 1, 0, '1990-03-08 12:51:44', '2009-09-06 10:01:05');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (52, 48, 46, 'Est ipsum accusamus qui rerum. Adipisci doloremque repellendus dolores ea blanditiis. Sint aut maiores consectetur voluptate dicta et. Minima molestias et assumenda fugiat necessitatibus. Quisquam sed ipsum alias iure rerum aut.', 0, 1, '2002-04-22 15:56:57', '2013-08-02 06:59:17');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (53, 68, 8, 'Omnis necessitatibus molestiae et. In nostrum vero facilis ullam. Sed dolorem corporis quia ut voluptate qui ducimus et. Modi saepe voluptatem ut delectus ut.', 1, 0, '2001-12-06 02:54:01', '2004-06-18 23:38:24');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (54, 12, 53, 'Cumque et commodi suscipit voluptates doloribus eveniet quam. Eligendi assumenda consectetur est. Aliquam asperiores qui repellat illo. Consequatur incidunt dolorum veniam qui perspiciatis possimus. Ea fugit quos et omnis ad.', 0, 1, '1989-06-21 19:00:41', '2010-12-16 17:00:06');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (55, 81, 99, 'Perferendis aut officiis ut accusantium atque. A illum molestias a voluptatem. Sed accusantium est id sit et ex. Est a qui at non et.', 0, 1, '2017-02-06 18:35:04', '1977-09-23 08:04:46');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (56, 9, 44, 'Nemo deserunt numquam ratione facilis sed excepturi sit. A autem ipsa optio corrupti molestiae. Ab ad accusamus officiis asperiores.', 1, 1, '1982-09-02 10:18:40', '2010-07-21 08:48:23');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (57, 44, 62, 'Illum quaerat deserunt consequatur delectus mollitia vel. Est officia qui modi laborum. Aut quae velit in dolor dicta autem.', 0, 1, '2001-01-08 04:10:35', '1982-05-28 08:31:27');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (58, 19, 11, 'Suscipit ut est est enim nesciunt. Non magnam officiis mollitia. Officiis accusantium id aliquam sunt. Odit eum tenetur consequatur eum aut nesciunt.', 0, 1, '1974-01-30 06:26:30', '1987-12-26 11:35:15');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (59, 18, 23, 'Ullam odio perferendis eum consectetur ut ducimus molestiae. Quo similique rerum rerum. Facilis est et aliquam debitis sed quae eos.', 1, 0, '2015-08-02 07:18:09', '1998-06-15 00:49:11');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (60, 36, 66, 'Quas ab id ea voluptatibus error voluptatem necessitatibus et. Minima eveniet libero ex. Quaerat ab exercitationem ea doloremque nihil. Dolorem voluptas qui tempora sint architecto ducimus.', 0, 0, '1970-08-23 23:16:52', '1972-05-18 08:30:18');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (61, 52, 1, 'Molestias molestiae alias ea quam ut. Corporis cumque consequatur deleniti qui repudiandae ea. Nostrum itaque dolor error autem numquam.', 0, 0, '1976-10-13 02:41:31', '2002-08-12 01:28:15');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (62, 72, 52, 'Sit aut itaque architecto sit dolorum optio consequuntur est. Veniam error ut vel est beatae. Ipsum quia ad aut.', 0, 1, '2008-03-17 20:48:39', '2021-07-15 07:18:52');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (63, 46, 78, 'Qui tempora reprehenderit perferendis. Laudantium voluptatibus fugiat pariatur et sint aspernatur. Quos sunt voluptas dolorem totam qui.', 1, 1, '1996-04-12 15:44:20', '1998-09-01 07:25:11');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (64, 71, 29, 'Omnis suscipit consequuntur consequatur. Adipisci adipisci at voluptas similique dolor. Est exercitationem fuga corrupti qui et alias et. Assumenda odio corrupti enim sequi in qui.', 0, 0, '2019-03-19 18:54:59', '2017-04-25 01:07:01');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (65, 13, 94, 'Saepe velit laboriosam atque in ut ea. Dolor ipsa ut fugit. Numquam aut ut id assumenda molestiae vel dignissimos voluptatem. Error atque illum voluptas est.', 1, 1, '2010-06-26 16:29:49', '2011-05-18 08:54:10');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (66, 53, 1, 'Aliquam nulla ipsam quam dolor id ducimus culpa. Atque et facilis rerum in a qui maxime consequatur. Mollitia quidem quam rerum. At ut nihil sed ullam ducimus recusandae.', 1, 1, '1984-10-13 21:46:33', '2018-07-27 21:27:26');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (67, 97, 20, 'Sed sunt accusamus maxime minus non. Fuga id non nobis. Consectetur voluptatum rerum animi aliquid eum non. Amet nulla sed quas vel illo.', 0, 1, '1987-08-22 19:59:18', '2019-03-17 01:30:16');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (68, 89, 60, 'Neque accusantium molestias labore incidunt sed qui ut error. Dolorem suscipit vel aut incidunt facere provident. Ut excepturi consequatur quia minima soluta dolorum.', 0, 0, '1980-04-19 06:50:27', '2000-06-15 00:18:58');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (69, 1, 91, 'Voluptas totam error aut placeat laborum adipisci laboriosam. Iusto non nobis molestiae corrupti eaque. Quia eum laborum debitis molestiae aut earum.', 0, 0, '1993-07-20 21:55:52', '2009-09-21 21:27:54');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (70, 45, 95, 'Aut neque quia ut incidunt a neque. Tenetur consequuntur nostrum nostrum asperiores. Ratione eligendi consequatur corporis quae rem qui officia. Laudantium explicabo qui sit dolorem consectetur fugit qui.', 0, 0, '2001-10-30 22:07:07', '1982-08-13 04:27:19');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (71, 38, 1, 'Deserunt consequuntur nisi ut molestiae. Explicabo dolorem ut quisquam quos magnam. Est reprehenderit et qui cumque culpa hic nostrum ullam.', 1, 0, '1992-02-05 15:07:48', '1990-12-05 10:06:26');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (72, 82, 35, 'Dolor ea possimus laudantium impedit ipsum voluptas. Quia aliquam libero totam eaque. Voluptatibus id asperiores similique illo.', 0, 0, '1995-12-11 03:01:50', '2008-07-18 13:39:14');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (73, 12, 12, 'Sed itaque consequatur nisi accusantium facilis quod. Recusandae dolores excepturi et et aut cupiditate quia. Aperiam minus molestiae et tempore est ipsam. Quaerat occaecati ab aperiam officia.', 1, 0, '1985-08-31 12:08:59', '1973-11-21 02:01:48');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (74, 53, 21, 'Blanditiis quia officiis est. Nobis perspiciatis excepturi fugiat ut totam in. Nisi hic quibusdam modi. Sunt atque rerum id odit sunt dolor. Iusto voluptatem molestiae aperiam.', 0, 1, '2019-09-19 17:58:08', '1989-09-03 09:43:07');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (75, 9, 87, 'Et iure quia qui ut. Reprehenderit sint velit nostrum reprehenderit voluptatem facilis. Non voluptatem eaque sit facere. Sit nihil perferendis sunt.', 1, 1, '1992-10-26 13:55:32', '1997-04-29 11:48:03');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (76, 67, 24, 'Soluta ullam commodi ut in. Occaecati ex a soluta earum. Reiciendis aut placeat mollitia rem nemo quia praesentium ducimus.', 0, 0, '2004-01-27 04:10:18', '2003-03-02 07:17:54');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (77, 53, 8, 'Omnis pariatur nihil ducimus ut aut. Rerum omnis suscipit perspiciatis dolores enim quibusdam. Velit consequuntur minus cum harum dolorum enim.', 0, 1, '1971-01-11 11:05:51', '2013-11-16 17:43:47');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (78, 39, 55, 'Vel consequatur nemo veniam tempore. Et eaque rem quaerat molestiae est dignissimos. Provident facilis molestiae repellendus magni corporis. Qui atque delectus voluptate.', 0, 0, '1990-09-15 10:24:29', '2020-09-26 14:13:14');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (79, 5, 44, 'Tempore quasi odit sequi. Aut repellendus ut eligendi incidunt est deleniti. Accusantium sunt in occaecati tenetur. Tempore autem et facilis quidem sequi.', 1, 0, '2019-02-12 03:56:27', '2022-03-03 07:45:08');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (80, 71, 31, 'Iure velit aut dolores autem velit. Ipsum molestiae aut omnis soluta blanditiis dicta placeat. Est pariatur et sed. Suscipit repellat eveniet dolores est.', 1, 0, '1972-06-11 21:41:33', '1970-09-22 22:49:52');


